PLIP 2780: textindexer
plone/plone.app.dexterity pull request #344
Opened 2022-04-04 10:33 UTC by jensens

Integration of `collective.textindexer` -> `plone.app.dexterity.textindexer`.
https://github.com/plone/Products.CMFPlone/issues/2780

2022-04-04 10:33 UTC, mister-roboto commented
@jensens thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-04-06 15:47 UTC, MrTango requested changes
docs need to be updated, broken links

2022-04-06 15:57 UTC, jensens commented
@jenkins-plone-org please run jobs

2022-04-06 17:19 UTC, MrTango approved these changes
Looks good, i suggested some link fixes to the new documentation, where the updated docs from collective.dexteritytextindexer live now, than it should be good to go.

2022-04-06 17:19 UTC, MrTango commented on docs/advanced/catalog-indexing-strategies.rst
> +See the `plone.app.dexterity.textindexer  <https://github.com/collective/plone.app.dexterity.textindexer>`_ package documentation for details and for information on how to use it via Python schema.
```suggestion
See the `/backend/indexing  <https://6-dev-docs.plone.org/backend/indexing>`_ documentation for details and for information on how to use it via Python schema.
```

2022-04-06 17:19 UTC, MrTango commented on docs/advanced/catalog-indexing-strategies.rst
> +So, you may need to explicitly add fields to SearchableText if you wish their information to be findable via the main search. There are all sorts of highly customizable ways to do this, but the easie
```suggestion
So, you may need to explicitly add fields to SearchableText if you wish their information to be findable via the main search. There are all sorts of highly customizable ways to do this, but the easiest is to use the `plone.app.dexterity.textindexer  <https://github.com/plone/plone.app.dexterity>`_ core package.
```

2022-04-06 17:20 UTC, MrTango commented
@pbauer you where on the failing tests, right?

2022-04-07 08:54 UTC, pbauer commented
tests are fixed and docs are updated.

2022-04-07 09:07 UTC, merged