Remove DeprecationWarning from a moved p.a.widgets import
plone/plone.app.dexterity pull request #387
Opened 2024-05-02 15:49 UTC by jensens

2024-05-02 15:49 UTC, mister-roboto commented
@jensens thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-05-02 15:51 UTC, jensens commented
@jenkins-plone-org please run jobs

2024-05-02 16:00 UTC, jensens commented
@jenkins-plone-org please run jobs

2024-05-03 06:42 UTC, jensens commented
@jenkins-plone-org please run jobs

2024-05-07 10:34 UTC, petschki requested changes

2024-05-07 10:34 UTC, petschki commented on plone/app/dexterity/behaviors/metadata.py
> +from plone.app.z3cform.widgets.select import SelectFieldWidget
The correct import for the former `SelectFieldWidget` is now `.widgets.select.Select2FieldWidget` ... see https://github.com/plone/plone.app.z3cform/blob/master/plone/app/z3cform/widget.py#L54 ... the `SelectFieldWidget` is a bare Bootstrap5 flavored `<select />`

2024-05-07 10:41 UTC, jensens commented
@jenkins-plone-org please run jobs

2024-05-07 10:46 UTC, petschki commented
CI tests for 6.0 should be dropped as this change targets Plone 6.1 only

2024-05-08 01:13 UTC, davisagli commented
@petschki If there are changes which are for 6.1 only, then a new maintenance branch needs to be created from current master and set as the source in https://github.com/plone/buildout.coredev/blob/6.0/sources.cfg /cc @mauritsvanrees 

Then something needs to happen to make mr.roboto notice the change -- is that manual or automatic @gforcada?

2024-05-08 05:02 UTC, petschki commented
branches from `sources.cfg` are picked automatically by mr.roboto ... @jensens could you create a maintenance branch here?

2024-05-10 14:20 UTC, jensens commented
@jenkins-plone-org please run jobs

2024-05-11 15:57 UTC, gforcada commented
@davisagli (and everyone anyway), `mr.roboto` indeed updates the branches automatically.

You can see the matrix of plone version / package / branch used in the following page:

https://jenkins.plone.org/roboto/branches

Note: red means that the package is checked out in `checkouts.cfg`

2024-05-12 17:49 UTC, merged